"""Storage abstractions.

Two primitives mirror the Modal design:

* ``FileStore``    -> blobs (uploads, results, posters); Modal Volume in prod.
* ``MetadataStore``-> small JSON-like job records; Modal Dict in prod.

Local in-process / filesystem implementations let the whole API run and be
tested without Modal. The Modal-backed implementations live in
``video-backend/modal_app.py``.

Paths are always generated server-side from opaque ids; a raw user filename is
never used in a filesystem path.
"""

from __future__ import annotations

import re
import threading
from collections.abc import Iterator
from pathlib import Path
from typing import Protocol, runtime_checkable

_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9_.-]")


def safe_segment(value: str) -> str:
    """Reduce an id to a filesystem-safe path segment.

    Opaque ids generated by the server are already safe; this is defence in
    depth so a crafted owner/job id can never escape the storage root.
    """
    cleaned = _SAFE_SEGMENT.sub("_", value).strip("._")
    if not cleaned:
        raise ValueError("empty path segment")
    return cleaned


# --- Path helpers (single source of truth for the volume layout) ---------


def source_path(owner_sub: str, job_id: str) -> str:
    # Extensionless on purpose: ffmpeg demuxes by content, not by filename.
    return f"uploads/{safe_segment(owner_sub)}/{safe_segment(job_id)}/source"


def result_path(owner_sub: str, job_id: str) -> str:
    return f"results/{safe_segment(owner_sub)}/{safe_segment(job_id)}/result"


def preview_path(owner_sub: str, job_id: str) -> str:
    return f"previews/{safe_segment(owner_sub)}/{safe_segment(job_id)}/poster"


def job_prefixes(owner_sub: str, job_id: str) -> list[str]:
    """All directories belonging to a job, for deletion."""
    s, j = safe_segment(owner_sub), safe_segment(job_id)
    return [
        f"uploads/{s}/{j}",
        f"results/{s}/{j}",
        f"previews/{s}/{j}",
    ]


# --- FileStore -----------------------------------------------------------


@runtime_checkable
class FileStore(Protocol):
    def write(self, path: str, data: bytes) -> None: ...
    def read(self, path: str) -> bytes: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def delete_prefix(self, prefix: str) -> None: ...
    def commit(self) -> None: ...
    def reload(self) -> None: ...


class LocalFileStore:
    """Filesystem-backed FileStore rooted at ``base_dir``."""

    def __init__(self, base_dir: str | Path) -> None:
        self._base = Path(base_dir).resolve()
        self._base.mkdir(parents=True, exist_ok=True)

    def _resolve(self, path: str) -> Path:
        target = (self._base / path).resolve()
        if not str(target).startswith(str(self._base)):
            raise ValueError("path escapes storage root")
        return target

    def write(self, path: str, data: bytes) -> None:
        target = self._resolve(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

    def read(self, path: str) -> bytes:
        return self._resolve(path).read_bytes()

    def exists(self, path: str) -> bool:
        return self._resolve(path).exists()

    def delete(self, path: str) -> None:
        target = self._resolve(path)
        if target.is_file():
            target.unlink(missing_ok=True)

    def delete_prefix(self, prefix: str) -> None:
        import shutil

        target = self._resolve(prefix)
        if target.is_dir():
            shutil.rmtree(target, ignore_errors=True)
        elif target.is_file():
            target.unlink(missing_ok=True)

    def commit(self) -> None:
        # No-op for a local filesystem; Modal Volume overrides this.
        return None

    def reload(self) -> None:
        return None


# --- MetadataStore -------------------------------------------------------


@runtime_checkable
class MetadataStore(Protocol):
    def get(self, key: str) -> dict | None: ...
    def put(self, key: str, value: dict) -> None: ...
    def delete(self, key: str) -> None: ...
    def contains(self, key: str) -> bool: ...
    def items(self) -> Iterator[tuple[str, dict]]: ...


class InMemoryMetadataStore:
    """Thread-safe dict-backed MetadataStore for local runs and tests."""

    def __init__(self) -> None:
        self._data: dict[str, dict] = {}
        self._lock = threading.RLock()

    def get(self, key: str) -> dict | None:
        with self._lock:
            value = self._data.get(key)
            return dict(value) if value is not None else None

    def put(self, key: str, value: dict) -> None:
        with self._lock:
            self._data[key] = dict(value)

    def delete(self, key: str) -> None:
        with self._lock:
            self._data.pop(key, None)

    def contains(self, key: str) -> bool:
        with self._lock:
            return key in self._data

    def items(self) -> Iterator[tuple[str, dict]]:
        with self._lock:
            snapshot = list(self._data.items())
        for key, value in snapshot:
            yield key, dict(value)
